version: "3"

services:

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:7.2-fpm
    container_name: app
    volumes:
      - .:/var/www/html
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
